### ISSUE TITLE
GFM support

### ISSUE THREAD

**Issue by pyrsmk** [fluxbb/commonmark#3]
The GFM extension is disabled by default and it seems the classes have been removed from the previous project.

What are the plans for the GFM syntax?

**Comment by franzliedke** [comment]
We implement the CommonMark syntax, not GFM.

CommonMark does have fenced code blocks and autolinks, though.

**Comment by pyrsmk** [comment]
Ah ok, didn't know that ;)

**Comment by pyrsmk** [comment]
You should remove the mention on the doc

**Comment by franzliedke** [comment]
[Done](https://github.com/fluxbb/commonmark/commit/f757c932d0983411567c90f29f57c6f771f030c2), thanks.
